### ISSUE TITLE
picking up enemy swords off the floor can lead to the sword being stuck under the map

### ISSUE THREAD

**Issue by isteals** [PotatoFaceJames/HtHCVR#25] opened 2019-11-09 16:06 UTC
sometimes i try pick up an enemy sword that is on the ground and it glitches under the map (unretreiveable). Same thing can happen to an enemy but they unfortunately dont lose the grip and they run about with a stretchy arm with the sword following under the map

**Comment by PotatoFaceJames** [comment] 2019-11-11 09:25
It should attach and set? Closing this for now as I can't reproduce it (even easily or after trying by spawning in new katana enemies)

**Closed by PotatoFaceJames** 2019-11-11 09:25 UTC
